name: Integracao Continua - IMC

on:
  push:   

jobs:
  executar-testes-em-nuvem:
    runs-on: ubuntu-latest 
    steps:
      - name: Passo 1 - Baixar o código atualizado do repositório
        uses: actions/checkout@v3

      - name: Passo 2 - Configurar o ecossistema do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Passo 3 - Instalar dependências e Jest
        run: npm install

      - name: Passo 4 - Executar a suíte de testes
        run: npm test